---
- name: Pre flight stuff.
  ansible.builtin.include_tasks: pre-flight.yml

- name: Set working directory
  ansible.builtin.set_fact:
    work_dir: /etc/apt/keyrings{{ key_armored | ternary('-armor', '') }}

- name: Download unarmored key.
  ansible.builtin.get_url:
    url: "{{ key_url }}"
    dest: /etc/apt/keyrings/{{ key_name }}
    owner: root
    group: root
    mode: '0644'
  when: not key_armored

- name: Download armored key.
  ansible.builtin.get_url:
    url: "{{ key_url }}"
    dest: /etc/apt/keyrings-armor/{{ key_name }}.asc
    owner: root
    group: root
    mode: '0644'
  when: key_armored
  notify: Dearmor key
