---
- name: Converge
  hosts: all
  vars:
    # key_name: syncthing-archive-keyring.gpg
    # key_url: https://syncthing.net/release-key.gpg
    key_name: docker-archive-keyring.gpg
    key_url: https://download.docker.com/linux/debian/gpg
    key_armored: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
  tasks:
    - name: Include apt_key.
      ansible.builtin.include_role:
        name: alecunsolo.apt_key
